name: .NET Core

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: 
      - develop
      - GA-*
env:
  MAIN_PROJECT: OneScript/OneScriptWeb.csproj
  SOLUTION: OneScript.sln
jobs:
  build-linux:
    defaults:
      run: 
        working-directory: src
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build
      run: dotnet build ${{env.MAIN_PROJECT}} -c Release -r linux-x64 -f netcoreapp3.1
    - name: Test
      run: dotnet test src/OneScriptWeb.Tests/OneScriptWeb.Tests.csproj --no-build --runtime=win-x64 -f netcoreapp3.1
  build-windows:
    runs-on: windows-latest
    defaults:
      run: 
        working-directory: src
        
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build
      run: dotnet build ${{env.MAIN_PROJECT}} -c Release -r win-x64 -f netcoreapp3.1
    - name: Test
      run: dotnet test src/OneScriptWeb.Tests/OneScriptWeb.Tests.csproj --no-build --runtime=win-x64 -f netcoreapp3.1
